# Server Port (Required for Cloud Hosting)
server.port=${PORT:8080}
app.frontend.url=${FRONTEND_URL}

# Database - Production
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.hikari.max-lifetime=60000

# Secrets
jwt.secret=${JWT_SECRET}
spring.ai.openai.api-key=${AI_API_KEY}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Google Sheets
google.sheets.web-app-url=${GS_WEB_APP_URL}
google.sheets.archive-data-url=${GS_ARCHIVE_DATA_URL}

# Hikari Tuning for Production
spring.datasource.hikari.maximum-pool-size=10